-- ============================================================================
-- PostgreSQL/PostGIS 初始化脚本
-- 作用：创建同步状态表、两类船舶档案表、最新船位表、MVT 函数和最小权限。
-- 执行账号：postgres（脚本内部会切换为 vessel_sync 创建业务对象）。
-- 可重复执行：表和索引使用 IF NOT EXISTS，函数使用 CREATE OR REPLACE。
-- ============================================================================

-- 任意语句失败时立即终止，防止继续执行后产生不完整的数据库结构。
\set ON_ERROR_STOP on

-- 初始化过程使用单一事务；任一步失败时，当前执行产生的变更全部回滚。
BEGIN;

-- 在当前 vessel_gis 数据库启用 PostGIS；已启用时只会输出 NOTICE。
CREATE EXTENSION IF NOT EXISTS postgis;
-- 禁止普通 PUBLIC 角色在 public schema 中创建对象，降低对象劫持风险。
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

-- 【前置检查】同步账号和瓦片只读账号必须由管理员提前创建。
DO $block$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'vessel_sync') THEN
        RAISE EXCEPTION '角色 vessel_sync 不存在，请先创建后再执行本脚本';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'vessel_tile') THEN
        RAISE EXCEPTION '角色 vessel_tile 不存在，请先创建后再执行本脚本';
    END IF;
END
$block$;

-- 【业务 schema】全部同步表和函数统一放在 vessel 中，并归 vessel_sync 所有。
CREATE SCHEMA IF NOT EXISTS vessel AUTHORIZATION vessel_sync;
ALTER SCHEMA vessel OWNER TO vessel_sync;

-- 后续对象由 vessel_sync 创建。vessel 必须位于 search_path 第一位，
-- 否则未限定 schema 的 CREATE TABLE 会错误尝试写入 pg_catalog。
SET ROLE vessel_sync;
SET search_path = vessel, pg_catalog, public;

-- 【兼容清理】删除早期包含用户参数的五参数瓦片函数；不存在时忽略。
DROP FUNCTION IF EXISTS boat_points_mvt(
    integer, integer, integer, bigint, double precision
);

-- 【同步状态】分别保存定位、双控船档案、乡镇船档案的增量水位和运行结果。
CREATE TABLE IF NOT EXISTS sync_state (
    stream_name          text PRIMARY KEY,
    watermark            timestamp without time zone,
    last_started_at      timestamp with time zone,
    last_succeeded_at    timestamp with time zone,
    rows_seen            bigint NOT NULL DEFAULT 0,
    rows_applied         bigint NOT NULL DEFAULT 0,
    last_error           text
);

-- 将中文说明写入 PostgreSQL 系统目录，便于使用 \d+ 或管理工具查看对象用途。
COMMENT ON TABLE sync_state IS 'MySQL 到 PostGIS 各数据流的同步水位及最近运行状态';
COMMENT ON COLUMN sync_state.watermark IS '最近一次成功处理的源数据时间水位';
COMMENT ON COLUMN sync_state.rows_seen IS '最近一次从 MySQL 读取的记录数';
COMMENT ON COLUMN sync_state.rows_applied IS '最近一次实际插入或更新的记录数';

-- 【乡镇船档案】镜像 MySQL bh_business.town_boat_base_mes 的切片所需字段。
CREATE TABLE IF NOT EXISTS town_boat_archive (
    source_id            bigint PRIMARY KEY,
    area_name            text,
    area_code            text,
    plan_boat_code       text,
    boat_usage           text,
    boat_total_length    numeric(10, 2),
    boat_length          numeric(10, 2),
    boat_total_power     numeric(10, 2),
    del_flag             boolean NOT NULL DEFAULT false,
    source_create_time   timestamp without time zone,
    source_update_time   timestamp without time zone,
    source_updated_at    timestamp without time zone NOT NULL,
    synced_at            timestamp with time zone NOT NULL DEFAULT clock_timestamp()
);

COMMENT ON TABLE town_boat_archive IS '乡镇船档案镜像，来源为 bh_business.town_boat_base_mes';
COMMENT ON COLUMN town_boat_archive.source_id IS 'MySQL 源表主键 id';
COMMENT ON COLUMN town_boat_archive.synced_at IS '本记录最近写入 PostGIS 的时间';

-- 船牌号用于把实时定位记录关联到乡镇船档案，仅索引未删除记录。
CREATE INDEX IF NOT EXISTS town_boat_archive_plan_boat_code_idx
    ON town_boat_archive (plan_boat_code)
    WHERE del_flag = false;

-- 【双控船档案】镜像 MySQL bh_business.dual_boat_base_mes 的切片所需字段。
CREATE TABLE IF NOT EXISTS dual_boat_archive (
    source_id            bigint PRIMARY KEY,
    boat_code            text,
    area_code            text,
    area_name            text,
    boat_name            text,
    boat_category        text,
    boat_length          numeric(10, 2),
    total_power          text,
    boat_type            text,
    work_type            text,
    del_flag             boolean NOT NULL DEFAULT false,
    source_create_time   timestamp without time zone,
    source_update_time   timestamp without time zone,
    source_updated_at    timestamp without time zone NOT NULL,
    synced_at            timestamp with time zone NOT NULL DEFAULT clock_timestamp()
);

COMMENT ON TABLE dual_boat_archive IS '双控船档案镜像，来源为 bh_business.dual_boat_base_mes';
COMMENT ON COLUMN dual_boat_archive.source_id IS 'MySQL 源表主键 id';
COMMENT ON COLUMN dual_boat_archive.synced_at IS '本记录最近写入 PostGIS 的时间';

-- 船名和船号用于把实时定位记录关联到双控船档案。
CREATE INDEX IF NOT EXISTS dual_boat_archive_boat_name_idx
    ON dual_boat_archive (boat_name)
    WHERE del_flag = false;

CREATE INDEX IF NOT EXISTS dual_boat_archive_boat_code_idx
    ON dual_boat_archive (boat_code)
    WHERE del_flag = false;

-- 【最新船位】每个 terminal_phone 只保留一条最新状态，不存历史轨迹。
CREATE TABLE IF NOT EXISTS boat_location_latest (
    feature_id           bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    terminal_phone       text PRIMARY KEY,
    boat_name            text,
    boat_manage_type     text,
    longitude            numeric(12, 8),
    latitude             numeric(12, 8),
    location_time        timestamp without time zone,
    speed                numeric(10, 2),
    direction            numeric(10, 2),
    terminal_type        text,
    del_flag             boolean NOT NULL DEFAULT false,
    remark               text,
    source_name          text,
    source_create_time   timestamp without time zone,
    source_update_time   timestamp without time zone,
    source_updated_at    timestamp without time zone NOT NULL,
    geom_4326            geometry(Point, 4326),
    geom_3857            geometry(Point, 3857),
    synced_at            timestamp with time zone NOT NULL DEFAULT clock_timestamp()
);

COMMENT ON TABLE boat_location_latest IS '渔船终端最新定位镜像，每个 terminal_phone 仅保留一条记录';
COMMENT ON COLUMN boat_location_latest.feature_id IS '稳定的 MVT 要素编号，用于热点抽稀排序';
COMMENT ON COLUMN boat_location_latest.geom_4326 IS 'WGS84 原始经纬度点，坐标系 EPSG:4326';
COMMENT ON COLUMN boat_location_latest.geom_3857 IS '用于 XYZ 瓦片空间检索的 Web Mercator 点，坐标系 EPSG:3857';

-- 空间索引用于按 XYZ 瓦片范围快速检索有效船位。
CREATE INDEX IF NOT EXISTS boat_location_latest_geom_3857_gix
    ON boat_location_latest USING gist (geom_3857)
    WHERE geom_3857 IS NOT NULL AND del_flag = false;

-- 时间索引用于离线时长过滤和最新报位时间检查。
CREATE INDEX IF NOT EXISTS boat_location_latest_location_time_idx
    ON boat_location_latest (location_time DESC);

-- 【MVT 主函数】参数依次为层级 z、列 x、行 y、允许的最大离线小时数。
-- 所有请求都只处理最近 24 小时内的有效报位；offline_hours 为 NULL 时使用该硬上限。
-- offline_hours 可进一步缩短显示范围；有效层级限定为 0～14。
CREATE OR REPLACE FUNCTION boat_points_mvt(
    z integer,
    x integer,
    y integer,
    offline_hours double precision
)
RETURNS bytea
LANGUAGE plpgsql
STABLE
PARALLEL SAFE
SECURITY DEFINER
SET search_path = pg_catalog, vessel, public
AS $function$
DECLARE
    result bytea;
BEGIN
    IF z < 0 OR z > 14 OR x < 0 OR y < 0
       OR x >= power(2::numeric, z) OR y >= power(2::numeric, z) THEN
        RAISE EXCEPTION '无效的 XYZ 瓦片坐标：z=%, x=%, y=%', z, x, y
            USING ERRCODE = '22023';
    END IF;

    IF offline_hours IS NOT NULL AND (offline_hours <= 0 OR offline_hours > 24) THEN
        RAISE EXCEPTION 'offline_hours 必须为 NULL 或位于 (0, 24] 范围内'
            USING ERRCODE = '22023';
    END IF;

    -- 每个返回要素都是真实船位，不生成聚合中心点。
    -- z0～z10 仅对船位过度重叠的热点网格抽稀；前端实际从 z1 开始使用。
    -- 每个瓦片固定划分为 32×32 个网格，每格约对应 16×16 屏幕像素，
    -- 与前端 12 像素船位图标的碰撞范围接近；随着层级增大，网格覆盖的实际地理范围自然缩小。
    -- 网格内不超过 4 艘时不抽稀；超过 4 艘时按定位时间稳定保留约 70% 的点位。
    -- z11～z14 不执行任何抽稀；前端 z11 使用全量切片，z12 起改用 WebSocket。
    -- bounds：计算当前瓦片边界、带缓冲查询边界，以及热点判断和抽稀参数。
    WITH bounds AS (
        SELECT
            ST_TileEnvelope(z, x, y) AS tile_geom,
            ST_TileEnvelope(z, x, y, margin => 64.0 / 4096.0) AS query_geom,
            -- 24 小时为全局显示硬上限；过期或无时间的记录不进入关联、计数和抽稀。
            timezone('Asia/Shanghai', statement_timestamp()) - interval '24 hours'
                AS visible_since,
            40075016.68557849::double precision
                / power(2::double precision, z)
                / 32.0 AS cell_size,
            -- 超过该数量才将网格认定为热点；数量较少时全部展示。
            4::bigint AS density_threshold,
            -- 热点网格保留比例；向上取整可确保实际保留数量不低于 70%。
            0.70::numeric AS retention_ratio
    ),
    -- eligible_locations：先强制执行删除标记、空间范围、24小时硬上限和用户时长过滤。
    -- MATERIALIZED 保证不符合条件的记录不会进入档案关联、热点计数或后续渲染处理。
    eligible_locations AS MATERIALIZED (
        SELECT
            l.*,
            b.tile_geom,
            b.cell_size,
            b.density_threshold,
            b.retention_ratio
        FROM boat_location_latest AS l
        CROSS JOIN bounds AS b
        WHERE l.del_flag = false
          AND l.geom_3857 IS NOT NULL
          AND l.geom_3857 && b.query_geom
          -- 超过 24 小时或没有定位时间的记录不参与任何后续处理及展示。
          AND l.location_time IS NOT NULL
          AND l.location_time >= b.visible_since
          AND (
              offline_hours IS NULL
              OR l.location_time >= timezone('Asia/Shanghai', statement_timestamp())
                  - make_interval(secs => offline_hours * 3600.0)
          )
    ),
    -- candidates：仅对合格船位进行档案关联，并计算网格船数和稳定序号。
    candidates AS (
        SELECT
            l.feature_id,
            COALESCE(l.terminal_type, '') AS "terminalType",
            l.terminal_phone AS "terminalPhone",
            COALESCE(l.source_name, '') AS "sourceName",
            COALESCE(l.boat_name, a.archive_boat_name, '') AS "boatName",
            l.longitude::double precision AS longitude,
            l.latitude::double precision AS latitude,
            COALESCE(l.speed, 0)::double precision AS speed,
            COALESCE(l.direction, 0)::double precision AS direction,
            COALESCE(to_char(l.location_time, 'YYYY-MM-DD HH24:MI:SS'), '') AS "locationTime",
            COALESCE(a.boat_type, '') AS "boatType",
            COALESCE(l.boat_manage_type, '') AS "boatManageType",
            -- 与 beihai-front 的 WebSocket 船型分类保持一致，供 MVT 复用原有图标和筛选。
            CASE
                WHEN l.boat_manage_type LIKE '%养殖%' THEN '养殖船'
                WHEN l.boat_manage_type LIKE '%双控%' THEN
                    CASE
                        WHEN COALESCE(a.total_power, '') ~ '^\s*[0-9]+(?:\.[0-9]+)?\s*$'
                             AND trim(a.total_power)::double precision >= 110 THEN '捕捞大船'
                        WHEN COALESCE(a.total_power, '') ~ '^\s*[0-9]+(?:\.[0-9]+)?\s*$'
                             AND trim(a.total_power)::double precision >= 44 THEN '捕捞中船'
                        ELSE '捕捞小船'
                    END
                ELSE '乡镇船舶'
            END AS "filterValue",
            COALESCE(a.total_power, '') AS "totalPower",
            COALESCE(a.boat_length, '') AS "boatLength",
            (a.source_id IS NOT NULL) AS "hasArchiveMes",
            CASE
                WHEN l.location_time IS NULL THEN '离线'
                -- 定位时间距当前北京时间不超过 2 小时（含边界）时为在线，否则为离线。
                WHEN l.location_time < timezone('Asia/Shanghai', statement_timestamp()) - interval '2 hours'
                    THEN '离线'
                ELSE '在线'
            END AS "lineType",
            COALESCE(a.area_code, '') AS "areaCode",
            COALESCE(a.boat_code, '') AS "boatCode",
            l.geom_3857,
            l.tile_geom,
            l.density_threshold,
            l.retention_ratio,
            count(*) OVER (
                PARTITION BY
                    floor(ST_X(l.geom_3857) / l.cell_size),
                    floor(ST_Y(l.geom_3857) / l.cell_size)
            ) AS cell_boat_count,
            row_number() OVER (
                PARTITION BY
                    floor(ST_X(l.geom_3857) / l.cell_size),
                    floor(ST_Y(l.geom_3857) / l.cell_size)
                -- 热点网格优先保留最新报位；时间相同时用 feature_id 保证结果稳定。
                ORDER BY l.location_time DESC NULLS LAST, l.feature_id
            ) AS density_rank
        FROM eligible_locations AS l
        LEFT JOIN LATERAL (
            -- 将双控船和乡镇船字段归一化；优先采用 boat_manage_type 对应的档案类型，
            -- 再按船名/船牌号匹配，只有船型明确时才使用 source_name=id 后备匹配。
            SELECT archive_candidate.*
            FROM (
                SELECT
                    'dual'::text AS archive_kind,
                    archive.source_id,
                    archive.boat_name AS archive_boat_name,
                    archive.boat_type,
                    archive.total_power,
                    archive.boat_length::text AS boat_length,
                    archive.area_code,
                    archive.boat_code,
                    archive.source_updated_at,
                    (archive.boat_name = l.boat_name) AS name_match,
                    (archive.source_id = CASE
                        WHEN l.source_name ~ '^[0-9]+$' THEN l.source_name::bigint
                        ELSE NULL
                    END) AS id_match
                FROM dual_boat_archive AS archive
                WHERE archive.del_flag = false
                  AND (
                      (
                          NULLIF(l.boat_name, '') IS NOT NULL
                          AND archive.boat_name = l.boat_name
                      )
                      OR (
                          l.boat_manage_type LIKE '%双控%'
                          AND archive.source_id = CASE
                              WHEN l.source_name ~ '^[0-9]+$' THEN l.source_name::bigint
                              ELSE NULL
                          END
                      )
                  )

                UNION ALL

                SELECT
                    'town'::text AS archive_kind,
                    archive.source_id,
                    archive.plan_boat_code AS archive_boat_name,
                    archive.boat_usage AS boat_type,
                    archive.boat_total_power::text AS total_power,
                    COALESCE(archive.boat_length, archive.boat_total_length)::text AS boat_length,
                    archive.area_code,
                    archive.plan_boat_code AS boat_code,
                    archive.source_updated_at,
                    (archive.plan_boat_code = l.boat_name) AS name_match,
                    (archive.source_id = CASE
                        WHEN l.source_name ~ '^[0-9]+$' THEN l.source_name::bigint
                        ELSE NULL
                    END) AS id_match
                FROM town_boat_archive AS archive
                WHERE archive.del_flag = false
                  AND (
                      (
                          NULLIF(l.boat_name, '') IS NOT NULL
                          AND archive.plan_boat_code = l.boat_name
                      )
                      OR (
                          l.boat_manage_type LIKE '%乡镇%'
                          AND archive.source_id = CASE
                              WHEN l.source_name ~ '^[0-9]+$' THEN l.source_name::bigint
                              ELSE NULL
                          END
                      )
                  )
            ) AS archive_candidate
            ORDER BY
                CASE
                    WHEN l.boat_manage_type LIKE '%双控%'
                         AND archive_candidate.archive_kind = 'dual' THEN 0
                    WHEN l.boat_manage_type LIKE '%乡镇%'
                         AND archive_candidate.archive_kind = 'town' THEN 0
                    ELSE 1
                END,
                archive_candidate.name_match DESC NULLS LAST,
                archive_candidate.id_match DESC NULLS LAST,
                archive_candidate.source_updated_at DESC,
                archive_candidate.source_id DESC,
                archive_candidate.archive_kind
            LIMIT 1
        ) AS a ON true
    ),
    -- features：z0～z10 的低密度网格全部保留，热点网格保留 ceil(船数 × 70%)；
    -- z11～z14 始终保留全部要素，然后将几何转换成 MVT 局部坐标。
    features AS (
        SELECT
            feature_id,
            "terminalType",
            "terminalPhone",
            "sourceName",
            "boatName",
            longitude,
            latitude,
            speed,
            direction,
            "locationTime",
            "boatType",
            "boatManageType",
            "filterValue",
            "totalPower",
            "boatLength",
            "hasArchiveMes",
            "lineType",
            "areaCode",
            "boatCode",
            ST_AsMVTGeom(geom_3857, tile_geom, 4096, 64, true) AS geom
        FROM candidates
        WHERE z >= 11
           OR cell_boat_count <= density_threshold
           OR density_rank <= ceil(cell_boat_count * retention_ratio)::bigint
    )
    -- 图层名固定为 boats，extent 为 4096，feature_id 作为 MVT 要素编号。
    SELECT ST_AsMVT(features, 'boats', 4096, 'geom', 'feature_id')
    INTO result
    FROM features;

    RETURN COALESCE(result, ''::bytea);
END
$function$;

COMMENT ON FUNCTION boat_points_mvt(integer, integer, integer, double precision)
    IS '生成最近24小时 boats 图层；2小时内在线；z0～10热点保留70%，z11～14不抽稀';

-- 【三参数兼容函数】未传离线小时数时仍只返回最近 24 小时船位。
CREATE OR REPLACE FUNCTION boat_points_mvt(z integer, x integer, y integer)
RETURNS bytea
LANGUAGE sql
STABLE
PARALLEL SAFE
SECURITY DEFINER
SET search_path = pg_catalog, vessel, public
AS $function$
    SELECT vessel.boat_points_mvt(z, x, y, NULL);
$function$;

COMMENT ON FUNCTION boat_points_mvt(integer, integer, integer)
    IS '使用24小时显示硬上限的三参数 MVT 兼容入口';

-- 【健康检查】返回船位数量、有效空间数量、两类档案数量及各同步流状态。
CREATE OR REPLACE FUNCTION tile_health()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, vessel, public
AS $function$
    SELECT jsonb_build_object(
        'status', 'ok',
        'boatCount', count(*),
        'validGeometryCount', count(*) FILTER (WHERE geom_3857 IS NOT NULL AND del_flag = false),
        'latestLocationTime', max(location_time),
        'lastSyncedAt', max(synced_at),
        'townArchiveCount', (SELECT count(*) FROM town_boat_archive WHERE del_flag = false),
        'dualArchiveCount', (SELECT count(*) FROM dual_boat_archive WHERE del_flag = false),
        'sync', COALESCE(
            (SELECT jsonb_object_agg(
                stream_name,
                jsonb_build_object(
                    'watermark', watermark,
                    'lastSucceededAt', last_succeeded_at,
                    'rowsSeen', rows_seen,
                    'rowsApplied', rows_applied,
                    'lastError', last_error
                )
            ) FROM sync_state),
            '{}'::jsonb
        )
    )
    FROM boat_location_latest;
$function$;

COMMENT ON FUNCTION tile_health()
    IS '返回船位数量、档案数量、最新定位时间和同步状态的健康检查信息';

-- 【最小权限】PUBLIC 无权访问业务对象，vessel_tile 只能执行瓦片和健康函数。
REVOKE ALL ON SCHEMA vessel FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA vessel FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA vessel FROM PUBLIC;
GRANT USAGE ON SCHEMA vessel TO vessel_tile;
GRANT EXECUTE ON FUNCTION boat_points_mvt(integer, integer, integer) TO vessel_tile;
GRANT EXECUTE ON FUNCTION boat_points_mvt(integer, integer, integer, double precision)
    TO vessel_tile;
GRANT EXECUTE ON FUNCTION tile_health() TO vessel_tile;

-- 【默认权限】确保 vessel_sync 后续新建表和函数不会自动开放给 PUBLIC。
ALTER DEFAULT PRIVILEGES FOR ROLE vessel_sync IN SCHEMA vessel
    REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE vessel_sync IN SCHEMA vessel
    REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

-- 恢复为最初执行脚本的管理员角色。
RESET ROLE;

-- 所有对象和权限都创建成功后再统一提交。
COMMIT;
